# Generated by Django 5.1.2 on 2024-10-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='name', max_length=10),
        ),
    ]
